import '@/shared/styled/global.scss'

import type { Metadata, ResolvingMetadata } from 'next'
import NextScript from 'next/script'
import { cookies, headers } from 'next/headers'
import { settingSService } from '@/services/setting.service'
import { getTranslation } from '@/locales/helper'
import FooterScripts from '@/views/global/footer-script'
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { Raleway, Playfair_Display } from 'next/font/google'
import { ISearchParams } from '@/app/types'
import AppHeaderSSR from '@/views/global/header.ssr'
// import AppFooter from '@/views/global/footer'

export interface IParamLocale {
  locale?: string
}

// const fontFamily = Roboto({
//   weight: ['400', '700'], // Chọn các độ đậm
//   subsets: ['latin', 'vietnamese'], // Đảm bảo hỗ trợ tiếng Việt nếu cần
//   style: ['normal', 'italic'] // Chọn kiểu chữ thường hoặc nghiêng,
// })

// <link rel="preconnect" href="https://fonts.googleapis.com" />
// <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
// <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />

// const fontFamily = Poppins({
//   weight: ['400', '700'], // Chọn các độ đậm
//   subsets: ['latin', 'latin-ext'], // Đảm bảo hỗ trợ tiếng Việt nếu cần
//   style: ['normal', 'italic'], // Chọn kiểu chữ thường hoặc nghiêng,
// });
type Props = {
  params: Promise<{ id: string } & IParamLocale>
  searchParams: Promise<ISearchParams>
}

export async function generateMetadata({ searchParams, params }: Props, parent: ResolvingMetadata): Promise<Metadata> {
  const p = await params
  // read route params
  const locale = p.locale
  const language = getTranslation(locale)
  return {
    title: language.TitleDefault
  }
}

// Register Google fonts and expose them as CSS variables:
// --font-primary => Playfair_Display
// --font-secondary => Raleway
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-primary'
})

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-secondary'
})

interface IRootLayoutProps {
  children: React.ReactNode
  params: { locale: string }
}

export default async function RootLayout(props: Readonly<IRootLayoutProps>) {
  const { children } = props
  const cookieStore = cookies()
  const p = await props.params
  const locale = p.locale ?? 'vn'
  const isEdit = cookieStore.has('edit-mode')
  const dataHomePage = await settingSService.getSettingdata(locale, ['Home', 'Global'], ['Setting', 'Footer'])
  const language = getTranslation(locale)
  return (
    <html>
      <head>
        {/*Meta Geo*/}
        {/* <base href="/edit/" /> */}
        {/* TODO chỉnh sửa nội dung ở đây */}
        {/* <meta name='DC.title' content='CÔNG TY DỊCH VỤ  BẢO VỆ ANH HÀO' />
        <meta name='geo.region' content='VN-SG' />
        <meta name='geo.placename' content='CÔNG TY DỊCH VỤ  BẢO VỆ ANH HÀO' />
        <meta name='geo.position' content='10.841908209639392:106.64609749259034' />
        <meta name='ICBM' content='10.841908209639392,106.64609749259034' />
        <meta name='DC.identifier' content='http://baoveanhhao.vn/' /> */}
        {/*Meta Geo*/}

        {/*Meta seo web*/}
        <meta
          name='keywords'
          content='https://weddingsbylan.com, weddingbylanle, wedding planner, wedding decoration, wedding event, wedding design, wedding services, wedding package, event decoration, engagement ceremony, wedding backdrop, wedding flowers, table decoration, full wedding service, wedding organizer, wedding stylist, luxury wedding, outdoor wedding, home wedding decoration, wedding gallery, wedding ideas, professional wedding planner, wedding in Ho Chi Minh City, wedding in Vietnam, Lan Le wedding, wedding decor, wedding party, wedding consultant, wedding ceremony, wedding planning, wedding by Lan Le'
        />
        <meta
          name='description'
          content='Weddingbylanle cung cấp dịch vụ lập kế hoạch, trang trí và chụp ảnh cưới chuyên nghiệp. Chúng tôi chuyên thiết kế đám cưới sáng tạo, tổ chức sự kiện trọn gói và trải nghiệm cá nhân hóa để ngày đặc biệt của bạn trở nên đáng nhớ.'
        />
        {/*Meta seo web*/}
      </head>

      <body className={`${playfair.variable} ${raleway.variable}`}>
        <div className='page-wrapper'>
          <AppHeaderSSR data={dataHomePage?.getData('Setting')} />
          {props.children}
          {/* <AppFooter footerData={dataHomePage?.getData('Footer')} settingData={dataHomePage?.getData('Setting')} /> */}
          <FooterScripts />
          {isEdit ? <NextScript src='/public/js/edit.mode.js' strategy='afterInteractive'></NextScript> : <></>}
        </div>
      </body>
    </html>
  )
}
