import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import { IPageProps } from "@/app/types";
export const metadata: Metadata = {
    title: "QUẢN TRỊ WEBSITE BẢO VỆ ANH HÀO!",
    description: "Generated by anhhao",
};

export default async function RootLayout({
    children, params
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>; // Tham số 'params' có thể là chuỗi hoặc không tồn tại
}>) {
    const p = await params;
    const locale = p.locale ?? 'vn';
    return (
        <html lang="en">
            <head>
                <base href={`/${locale}/admin/`} />
                <link rel="icon" href="/public/favicon.ico" />
            </head>
            <body>
                {children}
                <Script id="_3utkolss">
                    window._3utkolss = "84c0352d-c9c9-45a8-99ab-4bbcb163fe8f";
                </Script>
            </body>
        </html>
    );
}
